### ISSUE TITLE
Campaign finance dataset available online?

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/data-census#6]
Is the data available on the GR Open Data Portal or elsewhere online? If so document location as a comment on this issue.

http://data.grcity.us/
http://grcity.us

**Comment by diiq** [comment]
Submitted, awaiting review.

**Comment by Allen616** [comment]
Wondering why you remove the "help wanted" label?  Is it is redundant because it is an open task?

**Comment by diiq** [comment]
I assumed "help wanted" is the label people should look at when they want to find an issue to contribute to. They should not look at this issue, because our half of it is complete. There's nothing left to do except wait -- and that doesn't require much help :)

Have I misinterpreted the label? Should I put it back?

**Comment by diiq** [comment]
Update complete.
